name: test develop
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: git checkout
        uses: actions/checkout@v2

      - name: use Node.js 12.8.2
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: use mongo db
        uses: supercharge/mongodb-github-action@1.2.0
        with:
          mongodb-version: 4.2

      - run: npm install

      - run: npm run test
        env:
          CI: true
